name: Create release
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - 'src/info.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: get mod_version
      id: mod_version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'src/info.json'
        prop_path: 'version'

    - name: get mod name
      id: mod_name 
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'src/info.json'
        prop_path: 'name'
    
    - name: artifact name
      id: artifact_name
      run: |
        echo "name=${{ steps.mod_name.outputs.prop }}_${{ steps.mod_version.outputs.prop }}" >> $GITHUB_OUTPUT
 
    - name: get factorio_version
      id: factorio_version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'src/info.json'
        prop_path: 'factorio_version'
     
    - name: copy assets to dist
      run: |
        mkdir -p "./${{ steps.artifact_name.outputs.name }}"
        cp -r ./src/* "./${{ steps.artifact_name.outputs.name }}/"
          
    - name: Zip mod  
      run: |
        zip -r "./${{ steps.artifact_name.outputs.name }}.zip" "./${{ steps.artifact_name.outputs.name }}"
    
    # - name: Upload the mod on mods.factorio.com
    #   env:
    #     FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
    #   run: bash ./.scripts/upload.sh
    
    - uses: marvinpinto/action-automatic-releases@latest
      id: aar
      with:
        automatic_release_tag: "${{ steps.mod_version.outputs.prop }}"
        title: "${{ steps.factorio_version.outputs.prop }} for factorio ${{ steps.factorio_version.outputs.prop }}"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./${{ steps.artifact_name.outputs.name }}.zip
